### ISSUE TITLE
Tutorial code for Kernel Breakpoints hangs/crashes

### ISSUE THREAD

**Issue by dooglz** [RadeonOpenCompute/ROCm-Debugger#3]
System: Ubuntu 14.04.5, R9 390X, i7-4790K.
I'm trying to get kernel stepping working with the provided sample, I'm assuming the supplied brig and hssail in this repo have been compiled for debug. Other HSA test applications have worked fine without debugging.

Here are my Step and output:
install Rocm
cd to //opt/rocm/gpudebugsdk/samples/MatrixMultiplication
Run make
sudo //opt/rocm/gdb/bin/x86_64/rocm-gdb MatrixMul

> GNU gdb (GDB) 7.11
> AMD rocm-gdb 1.2.7
> This GDB was configured as "x86_64-pc-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see
> ...
> ROCm Configure Steps Done
> ....Certain GDB signals have been changed
> Reading symbols from MatrixMul...done.

(ROCm-gdb) start

> Temporary breakpoint 1 at 0x40c2d2: file MatrixMul.cpp, line 46.
> Starting program: /opt/rocm/gpudebugsdk/samples/MatrixMultiplication/MatrixMul
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> 
> Temporary breakpoint 1, main (argc=1, argv=0x7fffffffe4d8) at MatrixMul.cpp:46
> 46          bool doVerify = false;

(ROCm-gdb) b rocm:64

> GPU breakpoint 2 (Unknown GPU breakpoint type) pending.

(ROCm-gdb) c

At this point, the program will either do this and hang with 100% cpu usage on one core:

> Continuing.
> Initializing HSA runtime...
> [New Thread 0x7ffff6524700 (LWP 1975)]
> [New Thread 0x7ffff49b0700 (LWP 1976)]
> [ROCm-gdb: <Handling a SIGALRM - Used for GPU Debugging>]
> [ROCm-gdb: <Handling a SIGALRM - Used for GPU Debugging>]
> [ROCm-gdb: GPU Debugging has been successfully initialized]
> HSA device attributes:
>         name: CPU Device
>         type: CPU
>         chip ID: 0x0
>         HSA profile: Full
> HSA device attributes:
>         name: Hawaii
>         type: GPU
>         chip ID: 0x67b0
>         HSA profile: Base
> GPU kernel saved to temp_source
> [New Thread 0x7fffef7b4700 (LWP 1982)]
> [New Thread 0x7fffeefb3700 (LWP 1983)]
> Waiting for completion...

A few seconds go by..

> [Thread 0x7fffeefb3700 (LWP 1983) exited]

Or it will crash completely, requiring a reboot to get to the state before.

> Continuing.
> Initializing HSA runtime...
> [New Thread 0x7ffff6524700 (LWP 2142)]
> [New Thread 0x7ffff49b0700 (LWP 2143)]
> [ROCm-gdb: <Handling a SIGALRM - Used for GPU Debugging>]
> [ROCm-gdb: <Handling a SIGALRM - Used for GPU Debugging>]
> [ROCm-gdb: GPU Debugging has been successfully initialized]
> HSA device attributes:
>         name: CPU Device
>         type: CPU
>         chip ID: 0x0
>         HSA profile: Full
> HSA device attributes:
>         name: Hawaii
>         type: GPU
>         chip ID: 0x67b0
>         HSA profile: Base
> Error: Agent:Interception: Could not create a valid Queue, debugging will not workHSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.
> In ../Common/HSAResourceManager.cpp, line 261
> HSA status is not HSA_STATUS_SUCCESS.
> Error code: 4104.
> HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events..
> Error in HSAResourceManager::CreateDefaultQueue(): Create queue failed.
> In ../Common/HSAResourceManager.cpp, line 273
> HSA status is not HSA_STATUS_SUCCESS.
> Error code: 4103.
> HSA_STATUS_ERROR_INVALID_QUEUE: The queue is invalid..
> Error in HSAResourceManager::CreateDefaultQueue(): hsa_amd_profiling_set_profiler_enabled() failed.
> RunTest(): Error on creating default queue.
> [Thread 0x7ffff49b0700 (LWP 2143) exited]
> [Thread 0x7ffff6524700 (LWP 2142) exited]
> warning: Temporarily disabling breakpoints for unloaded shared library "//opt/rocm/gdb/bin/x86_64/../../../gpudebugsdk/lib/x86_64/libAMDHSADebugAgent-x64.so"
> 
> Thread 1 "MatrixMul" received signal SIGSEGV, Segmentation fault.
> 0x00007fffefdd0721 in ?? ()
> (ROCm-gdb)

**Comment by bpurnomo** [comment]
Thanks for this report.  R9 390x (codenamed Hawaii) is not supported by the debugger.  We will address this issue in a later version of the debugger by bailing out early and reporting to users about unsupported devices.
