### ISSUE TITLE
Cannot find gpudebugsdk/bin directory

### ISSUE THREAD

**Issue by zjing14** [RadeonOpenCompute/ROCm-Debugger#7]
I am looking for rocm-gdb-debug-flags.sh in gpudebugsdk/bin. However, I cannot find gpudebugsdk/bin directory in either git or dpkg.

**Comment by bpurnomo** [comment]
The script was provided to simply set all the env variables needed to compile for debug and was only relevant to hcc-hsail. It was removed since hcc-hsail is no longer present in the rocm 1.4 package.

If you are using hcc-hsail, you can find the script in one of the older release branches.
